const { Joi: JoiValidation } = require('express-validation')
const DateExtension = require('@joi/date');
const RegexUtil = require('../utils/RegexUtil');
const Constants = require('../constants');

const Joi = JoiValidation.extend(DateExtension);

module.exports = {
  create: {
    body: Joi.object({
      vehicle_type: Joi.string().valid(Constants.VEHICLE_TYPE_CAR, Constants.VEHICLE_TYPE_MOTOR).allow(null, ''),
      branch_id: Joi.number().integer().min(0).allow(null),
      customer_id: Joi.number().integer().min(0).allow(null),
      fullname: Joi.string().min(3).max(100).required(),
      email: Joi.string().email().allow(null, ''),
      phone: Joi.string().regex(RegexUtil.phoneRegex).required(),
      birthday: Joi.date().format().allow(null, ''),
      identity_number: Joi.string().regex(RegexUtil.identityRegex).allow(null, ''),
      identity_date: Joi.date().format().allow(null, ''),
      driver_licence_number: Joi.string().allow(null, ''),
      driver_licence_date: Joi.date().format().allow(null, ''),
      address: Joi.string().min(3).max(255).allow(null, ''),
      customer_note: Joi.string().max(1000).allow(null, ''),
      trust_score: Joi.number().integer().min(0).allow(null),
      approve_by: Joi.number().integer().min(0).allow(null),
      approve_status: Joi.number().integer().min(0).allow(null),
      approve_note: Joi.string().allow(null, ''),
      estimate_branch_vehicle_id: Joi.number().integer().min(0).allow(null),
      actual_branch_vehicle_id: Joi.number().integer().min(1).allow(null),
      estimate_price: Joi.number().integer().min(0),
      actual_price: Joi.number().integer().min(0),
      receive_note: Joi.string().max(255).allow(null, ''),
      return_note: Joi.string().max(255).allow(null, ''),
      estimate_deposit_paper: Joi.string().max(255).allow(null, ''),
      estimate_deposit_asset: Joi.string().max(255).allow(null, ''),
      reason_rental: Joi.string().max(255).allow(null, ''),
      receive_type: Joi.string().valid(Constants.RECEIVE_TYPE_GARA, Constants.RECEIVE_TYPE_HOME, Constants.RECEIVE_TYPE_ADDRESS).allow(null, ''),
      receive_address: Joi.string().max(255).allow(null, ''),
      estimate_receive_datetime: Joi.date().format().allow(null, ''),
      estimate_return_datetime: Joi.date().format().allow(null, ''),
      estimate_rental_duration: Joi.string().regex(RegexUtil.durationRegex).allow(0, ''),
      receive_km: Joi.number().integer().min(0),
      receive_fuel: Joi.number().min(0).max(100).allow('', null),
      return_km: Joi.number().integer().min(0),
      return_fuel: Joi.number().min(0).max(100).allow('', null),
      give_user_id: Joi.number().integer().min(0).allow(null),
      actual_receive_datetime: Joi.alternatives().conditional('actual_return_datetime', {
        is: Joi.date().format(),
        then: Joi.date().format().required(),
        otherwise: Joi.date().format().allow('', null),
      }),
      actual_return_datetime: Joi.date().format().allow('', null),
      actual_rental_duration: Joi.string().regex(RegexUtil.durationRegex).allow(0, ''),
      return_user_id: Joi.number().integer().min(1).allow(null),
      deposit: Joi.object().keys({
        [Constants.DEPOSIT_IDENTITY_PAPER]: Joi.string().allow(null, ''),
        [Constants.DEPOSIT_IDENTITY_PAPER_NOTE]: Joi.string().allow(null, ''),
        [Constants.DEPOSIT_MOTOR]: Joi.string().allow(null, ''),
        [Constants.DEPOSIT_MOTOR_REGISTRATION]: Joi.string().allow(null, ''),
        [Constants.DEPOSIT_CASH]: Joi.number().integer().min(0).allow(null),
        [Constants.DEPOSIT_OTHER]: Joi.string().allow(null, ''),
        [`${Constants.DEPOSIT_IDENTITY_PAPER}_returned`]: Joi.boolean().allow(null),
        [`${Constants.DEPOSIT_MOTOR}_returned`]: Joi.boolean().allow(null),
        [`${Constants.DEPOSIT_MOTOR_REGISTRATION}_returned`]: Joi.boolean().allow(null),
        [`${Constants.DEPOSIT_CASH}_returned`]: Joi.boolean().allow(null),
      }).unknown(true),
      level: Joi.string().max(2).allow(''),
      source: Joi.string().max(50).allow(''),
      saler_id: Joi.number().integer().min(0).allow(null),
      prepay: Joi.number().integer().min(0).allow(null),
      payment_method: Joi.string().allow(null, ""),
      other_costs: Joi.array().items(Joi.object({
        code: Joi.string().required(),
        cost: Joi.number().integer().min(1000).required(),
        note: Joi.string().allow(null, ''),
      })).allow(null),
      vat: Joi.object().keys({
        company_name: Joi.string().allow(null, ''),
        company_tax: Joi.string().allow(null, ''),
        company_address: Joi.string().allow(null, ''),
        company_email: Joi.string().allow(null, ''),
      }).allow(null),
      customer_image: Joi.object().keys({
        [Constants.CUSTOMER_IMAGE_IDENTITY_FRONT]: Joi.string().allow(null, ''),
        [Constants.CUSTOMER_IMAGE_IDENTITY_BACK]: Joi.string().allow(null, ''),
        [Constants.CUSTOMER_IMAGE_DRIVER_LICENCE_FRONT]: Joi.string().allow(null, ''),
        [Constants.CUSTOMER_IMAGE_DRIVER_LICENCE_BACK]: Joi.string().allow(null, ''),
        [Constants.CUSTOMER_IMAGE_HOUSE_HOLD]: Joi.string().allow(null, ''),
      }).unknown(true),
      before_car_image: Joi.object().keys({
        [Constants.CAR_IMAGE_FRONT]: Joi.string().allow(null, ''),
        [Constants.CAR_IMAGE_BACK]: Joi.string().allow(null, ''),
        [Constants.CAR_IMAGE_RIGHT]: Joi.string().allow(null, ''),
        [Constants.CAR_IMAGE_LEFT]: Joi.string().allow(null, ''),
      }).unknown(true),
      after_car_image: Joi.object().keys({
        [Constants.CAR_IMAGE_FRONT]: Joi.string().allow(null, ''),
        [Constants.CAR_IMAGE_BACK]: Joi.string().allow(null, ''),
        [Constants.CAR_IMAGE_RIGHT]: Joi.string().allow(null, ''),
        [Constants.CAR_IMAGE_LEFT]: Joi.string().allow(null, ''),
      }).unknown(true),
      contract_sign_date: Joi.date().format().allow(null, ''),
      contract_created_by: Joi.number().integer().min(0).allow(null),
      booking_paper: Joi.object().keys({
        [Constants.BOOKING_CUSTOMER_CONTRACT]: Joi.string().allow(null, ''),
        [Constants.BOOKING_RECEIVE_REPORT]: Joi.string().allow(null, ''),
      }).unknown(true),
      booking_contract_images: Joi.array().items(Joi.string()).allow(null),
      return_customer_assets: Joi.boolean().allow(),
      hold_customer_note: Joi.string().allow(null, ''),
      hold_customer_return_date: Joi.date().format('YYYY-MM-DD').allow(null, ''),
      hold_customer_reason: Joi.string().allow(null, ''),
      vehicle_full: Joi.boolean().allow(),
      receive_vehicle_status: Joi.string().allow(null, ''),
      return_vehicle_same: Joi.boolean().allow(),
      return_vehicle_status: Joi.string().allow(null, ''),
      return_etc_balance: Joi.number().integer().allow(0, null),
      receive_etc_balance: Joi.number().integer().allow(0, null),
      remain_amount: Joi.number().integer().allow(0, null),
      estimate_delivery_fee: Joi.number().integer().min(0).allow(null),
      delivery_fee: Joi.number().integer().min(0).allow(null),
      insurance_fee: Joi.number().integer().min(0).allow(null),
      deposit_images: Joi.array().items(Joi.string()).allow(null),
      booking_status: Joi.number().integer().allow(null, 0),
      estimate_add_ons: Joi.array().items(Joi.object({
        code: Joi.string().required(),
        cost: Joi.number().integer().required(),
        unit: Joi.string().allow(null, ''),
        note: Joi.string().allow(null, ''),
      })).allow(null),
      add_ons: Joi.array().items(Joi.object({
        code: Joi.string().required(),
        cost: Joi.number().integer().required(),
        unit: Joi.string().allow(null, ''),
        note: Joi.string().allow(null, ''),
      })).allow(null),
      customer_other_document_files: Joi.array().items(Joi.string()).allow(null),
      discount_code: Joi.string().allow(null, ''),
      discount_amount: Joi.number().integer().min(0).allow(null),
      estimate_discount_amount: Joi.number().integer().min(0).allow(null),
      vat_cost: Joi.number().integer().min(0).allow(null),
      estimate_vat_cost: Joi.number().integer().min(0).allow(null),
      operation_costs: Joi.array().items(Joi.object({
        code: Joi.string(),
        cost: Joi.number().integer().min(0),
        note: Joi.string().allow(null, ''),
      })).allow(null),
      post_operation_costs: Joi.array().items(Joi.object({
        code: Joi.string(),
        cost: Joi.number().integer().min(0),
        note: Joi.string().allow(null, ''),
      })).allow(null),
      final_note: Joi.string().allow(null, ''),
      estimate_prepay: Joi.number().integer().min(0).allow(null),
      total_amount: Joi.number().integer().min(0).allow(null),
      estimate_total_amount: Joi.number().integer().min(0).allow(null),
      estimate_after_discount_amount: Joi.number().integer().min(0).allow(null),
      estimate_total_addon_amount: Joi.number().integer().min(0).allow(null),
      total_addon_amount: Joi.number().integer().min(0).allow(null),
      contract_receive_datetime: Joi.date().format().allow(null, ''),
      contract_return_datetime: Joi.date().format().allow(null, ''),
      contract_rental_duration: Joi.string().allow(null, ''),
      liquid_total_addon: Joi.number().integer().min(0).allow(null),
      liquid_total_amount: Joi.number().integer().min(0).allow(null),
      liquid_total_amount_after_settlement: Joi.number().integer().min(0).allow(null),
      liquid_paid_amount: Joi.number().integer().min(0).allow(null),
      liquid_total_amount_left: Joi.number().integer().min(0).allow(null),
    }),
  },
  update: {
    body: Joi.object({
      vehicle_type: Joi.string().valid(Constants.VEHICLE_TYPE_CAR, Constants.VEHICLE_TYPE_MOTOR).allow(null, ''),
      branch_id: Joi.number().integer().min(0).allow(null),
      customer_id: Joi.number().integer().min(0).allow(null),
      fullname: Joi.string().min(3).max(100),
      email: Joi.string().email().allow(null, ''),
      phone: Joi.string().regex(RegexUtil.phoneRegex),
      birthday: Joi.date().format().allow(null, ''),
      identity_number: Joi.string().regex(RegexUtil.identityRegex).allow(null, ''),
      identity_date: Joi.date().format().allow(null, ''),
      driver_licence_number: Joi.string().allow(null, ''),
      driver_licence_date: Joi.date().format().allow(null, ''),
      address: Joi.string().min(3).max(255).allow(null, ''),
      customer_note: Joi.string().max(1000).allow(null, ''),
      trust_score: Joi.number().integer().min(0).allow(null),
      approve_by: Joi.number().integer().min(0).allow(null),
      approve_status: Joi.number().integer().min(0).allow(null),
      approve_note: Joi.string().allow(null, ''),
      estimate_branch_vehicle_id: Joi.number().integer().min(0).allow(null),
      actual_branch_vehicle_id: Joi.number().integer().min(1).allow(null),
      estimate_price: Joi.number().integer().min(0),
      actual_price: Joi.number().integer().min(0),
      receive_note: Joi.string().max(255).allow(null, ''),
      return_note: Joi.string().max(255).allow(null, ''),
      reason_rental: Joi.string().max(255).allow(null, ''),
      estimate_deposit_paper: Joi.string().max(255).allow(null, ''),
      estimate_deposit_asset: Joi.string().max(255).allow(null, ''),
      receive_type: Joi.string().valid(Constants.RECEIVE_TYPE_GARA, Constants.RECEIVE_TYPE_HOME, Constants.RECEIVE_TYPE_ADDRESS).allow(null, ''),
      receive_address: Joi.string().max(255).allow(null, ''),
      estimate_receive_datetime: Joi.date().format().allow(null, ''),
      estimate_return_datetime: Joi.date().format().allow(null, ''),
      estimate_rental_duration: Joi.string().regex(RegexUtil.durationRegex).allow(0, ''),
      receive_km: Joi.number().integer().min(0),
      receive_fuel: Joi.number().min(0).max(100).allow('', null),
      return_km: Joi.number().integer().min(0),
      return_fuel: Joi.number().min(0).max(100).allow('', null),
      give_user_id: Joi.number().integer().min(0).allow(null),
      actual_receive_datetime: Joi.date().format().allow('', null),
      actual_return_datetime: Joi.date().format().allow('', null),
      actual_rental_duration: Joi.string().regex(RegexUtil.durationRegex).allow(0, ''),
      return_user_id: Joi.number().integer().min(1).allow(null),
      level: Joi.string().max(2).allow(''),
      source: Joi.string().max(50).allow(''),
      saler_id: Joi.number().integer().min(0).allow(null),
      prepay: Joi.number().integer().min(0).allow(null),
      payment_method: Joi.string().allow(null, ""),
      deposit: Joi.object().keys({
        [Constants.DEPOSIT_MOTOR]: Joi.string().allow(null, ''),
        [Constants.DEPOSIT_MOTOR_REGISTRATION]: Joi.string().allow(null, ''),
        [Constants.DEPOSIT_CASH]: Joi.number().integer().min(0).allow(null),
        [Constants.DEPOSIT_OTHER]: Joi.string().allow(null, ''),
        [`${Constants.DEPOSIT_IDENTITY_PAPER}_returned`]: Joi.boolean().allow(null),
        [`${Constants.DEPOSIT_MOTOR}_returned`]: Joi.boolean().allow(null),
        [`${Constants.DEPOSIT_MOTOR_REGISTRATION}_returned`]: Joi.boolean().allow(null),
        [`${Constants.DEPOSIT_CASH}_returned`]: Joi.boolean().allow(null),
      }).unknown(true),
      other_costs: Joi.array().items(Joi.object({
        code: Joi.string(),
        cost: Joi.number().integer().min(1000),
        note: Joi.string().allow(null, ''),
      })).allow(null),
      vat: Joi.object().keys({
        company_name: Joi.string().allow(null, ''),
        company_tax: Joi.string().allow(null, ''),
        company_address: Joi.string().allow(null, ''),
        company_email: Joi.string().allow(null, ''),
      }).allow(null),
      customer_image: Joi.object().keys({
        [Constants.CUSTOMER_IMAGE_IDENTITY_FRONT]: Joi.string().allow(null, ''),
        [Constants.CUSTOMER_IMAGE_IDENTITY_BACK]: Joi.string().allow(null, ''),
        [Constants.CUSTOMER_IMAGE_DRIVER_LICENCE_FRONT]: Joi.string().allow(null, ''),
        [Constants.CUSTOMER_IMAGE_DRIVER_LICENCE_BACK]: Joi.string().allow(null, ''),
        [Constants.CUSTOMER_IMAGE_HOUSE_HOLD]: Joi.string().allow(null, ''),
      }).unknown(true),
      before_car_image: Joi.object().keys({
        [Constants.CAR_IMAGE_FRONT]: Joi.string().allow(null, ''),
        [Constants.CAR_IMAGE_BACK]: Joi.string().allow(null, ''),
        [Constants.CAR_IMAGE_RIGHT]: Joi.string().allow(null, ''),
        [Constants.CAR_IMAGE_LEFT]: Joi.string().allow(null, ''),
        [Constants.CAR_IMAGE_INTERIOR]: Joi.string().allow(null, ''),
        [Constants.CAR_IMAGE_FUEL]: Joi.string().allow(null, ''),
        [Constants.CAR_VIDEO]: Joi.string().allow(null, ''),
      }).unknown(true),
      after_car_image: Joi.object().keys({
        [Constants.CAR_IMAGE_FRONT]: Joi.string().allow(null, ''),
        [Constants.CAR_IMAGE_BACK]: Joi.string().allow(null, ''),
        [Constants.CAR_IMAGE_RIGHT]: Joi.string().allow(null, ''),
        [Constants.CAR_IMAGE_LEFT]: Joi.string().allow(null, ''),
        [Constants.CAR_IMAGE_INTERIOR]: Joi.string().allow(null, ''),
        [Constants.CAR_IMAGE_FUEL]: Joi.string().allow(null, ''),
        [Constants.CAR_VIDEO]: Joi.string().allow(null, ''),
      }).unknown(true),
      contract_sign_date: Joi.date().format().allow(null, ''),
      contract_created_by: Joi.number().integer().min(0).allow(null),
      booking_paper: Joi.object().keys({
        [Constants.BOOKING_CUSTOMER_CONTRACT]: Joi.string().allow(null, ''),
        [Constants.BOOKING_RECEIVE_REPORT]: Joi.string().allow(null, ''),
      }).unknown(true),
      booking_contract_images: Joi.array().items(Joi.string()).allow(null),
      return_customer_assets: Joi.boolean().allow(),
      hold_customer_note: Joi.string().allow(null, ''),
      hold_customer_return_date: Joi.date().format('YYYY-MM-DD').allow(null, ''),
      hold_customer_reason: Joi.string().allow(null, ''),
      vehicle_full: Joi.boolean().allow(),
      receive_vehicle_status: Joi.string().allow(null, ''),
      return_vehicle_same: Joi.boolean().allow(),
      return_vehicle_status: Joi.string().allow(null, ''),
      return_etc_balance: Joi.number().integer().allow(0, null),
      receive_etc_balance: Joi.number().integer().allow(0, null),
      remain_amount: Joi.number().integer().allow(0, null),
      estimate_delivery_fee: Joi.number().integer().min(0).allow(null),
      delivery_fee: Joi.number().integer().min(0).allow(null),
      insurance_fee: Joi.number().integer().min(0).allow(null),
      deposit_images: Joi.array().items(Joi.string()).allow(null),
      booking_status: Joi.number().integer().allow(null, 0),
      estimate_add_ons: Joi.array().items(Joi.object({
        code: Joi.string().required(),
        cost: Joi.number().integer().required(),
        unit: Joi.string().allow(null, ''),
        note: Joi.string().allow(null, ''),
      })).allow(null),
      add_ons: Joi.array().items(Joi.object({
        code: Joi.string().required(),
        cost: Joi.number().integer().required(),
        unit: Joi.string().allow(null, ''),
        note: Joi.string().allow(null, ''),
      })).allow(null),
      customer_other_document_files: Joi.array().items(Joi.string()).allow(null),
      discount_code: Joi.string().allow(null, ''),
      discount_amount: Joi.number().integer().min(0).allow(null),
      estimate_discount_amount: Joi.number().integer().min(0).allow(null),
      vat_cost: Joi.number().integer().min(0).allow(null),
      estimate_vat_cost: Joi.number().integer().min(0).allow(null),
      operation_costs: Joi.array().items(Joi.object({
        code: Joi.string(),
        cost: Joi.number().integer().min(0),
        note: Joi.string().allow(null, ''),
      })).allow(null),
      post_operation_costs: Joi.array().items(Joi.object({
        code: Joi.string(),
        cost: Joi.number().integer().min(0),
        note: Joi.string().allow(null, ''),
      })).allow(null),
      final_note: Joi.string().allow(null, ''),
      estimate_prepay: Joi.number().integer().min(0).allow(null),
      total_amount: Joi.number().integer().min(0).allow(null),
      estimate_total_amount: Joi.number().integer().min(0).allow(null),
      estimate_after_discount_amount: Joi.number().integer().min(0).allow(null),
      estimate_total_addon_amount: Joi.number().integer().min(0).allow(null),
      total_addon_amount: Joi.number().integer().min(0).allow(null),
      contract_receive_datetime: Joi.date().format().allow(null, ''),
      contract_return_datetime: Joi.date().format().allow(null, ''),
      contract_rental_duration: Joi.string().allow(null, ''),
      liquid_total_addon: Joi.number().integer().min(0).allow(null),
      liquid_total_amount: Joi.number().integer().min(0).allow(null),
      liquid_total_amount_after_settlement: Joi.number().integer().min(0).allow(null),
      liquid_paid_amount: Joi.number().integer().min(0).allow(null),
      liquid_total_amount_left: Joi.number().integer().min(0).allow(null),
    }),
  },
  createQuickBooking: {
    body: Joi.object({
      fullname: Joi.string().min(3).max(100).required(),
      phone: Joi.string().regex(RegexUtil.phoneRegex).required(),
      estimate_branch_vehicle_id: Joi.number().integer().min(0).required(),
      estimate_receive_datetime: Joi.date().format().required(),
      estimate_return_datetime: Joi.date().format().required(),
      level: Joi.string().max(2).allow('L4', 'L5', 'L6', 'L7', 'L8').required(),
      booked_status: Joi.string().valid(Constants.BOOKED_STATUS_DEPOSIT, Constants.BOOKED_STATUS_HOLD, Constants.BOOKED_STATUS_PAID100).required(),
    })
  }
}
