const { Joi } = require('express-validation')
const { latLngRegex, timeRegex } = require('../utils/RegexUtil')
const constants = require('../constants');

module.exports = {
  create: {
    body: Joi.object({
      name: Joi.string().max(255).required(),
      code: Joi.string().max(255).regex(RegExp(/^[\d\w]+$/)).required(),
      province_id: Joi.number().integer().min(0).required(),
      district_id: Joi.number().integer().min(0).required(),
      address: Joi.string().max(255).required(),
      latlng: Joi.string().max(100).regex(RegExp(latLngRegex)).allow('', null),
      rental_time_from: Joi.string().regex(RegExp(timeRegex)).allow('', null),
      rental_time_to: Joi.string().regex(RegExp(timeRegex)).allow('', null),
      limit_km: Joi.number().integer().min(0),
      overkm_fee: Joi.number().integer().min(0),
      overtime_fee: Joi.number().integer().min(0),
      free_delivery_km: Joi.number().integer().min(0),
      delivery_fee: Joi.number().integer().min(0),
      procedure: Joi.object().keys({
        [constants.PROCEDURE_IDENTITY]: Joi.valid(constants.PROCEDURE_TYPE_HOLD, constants.PROCEDURE_TYPE_VERIFY).allow(null, '').required(),
        [constants.PROCEDURE_HOUSEHOLD]: Joi.valid(constants.PROCEDURE_TYPE_HOLD, constants.PROCEDURE_TYPE_VERIFY).allow(null, '').required(),
        [constants.PROCEDURE_DRIVER_LICENCE]: Joi.valid(constants.PROCEDURE_TYPE_HOLD, constants.PROCEDURE_TYPE_VERIFY).allow(null, '').required(),
        [constants.PROCEDURE_DEPOSIT]: Joi.valid(constants.PROCEDURE_TYPE_HOLD, constants.PROCEDURE_TYPE_VERIFY).allow(null, '').required(),
        [constants.PROCEDURE_LABOR_CONTRACT]: Joi.valid(constants.PROCEDURE_TYPE_HOLD, constants.PROCEDURE_TYPE_VERIFY).allow(null, '').required(),
        [constants.PROCEDURE_OTHER]: Joi.valid(constants.PROCEDURE_TYPE_HOLD, constants.PROCEDURE_TYPE_VERIFY).allow(null, '').required(),
        [constants.PROCEDURE_IDENTITY + '_note']: Joi.string().allow(null, ''),
        [constants.PROCEDURE_HOUSEHOLD + '_note']: Joi.string().allow(null, ''),
        [constants.PROCEDURE_DRIVER_LICENCE + '_note']: Joi.string().allow(null, ''),
        [constants.PROCEDURE_DEPOSIT + '_note']: Joi.string().allow(null, ''),
        [constants.PROCEDURE_LABOR_CONTRACT + '_note']: Joi.string().allow(null, ''),
        [constants.PROCEDURE_OTHER + '_note']: Joi.string().allow(null, ''),
      }).unknown(true).allow(null).required(),
      holiday_event_price: Joi.object().keys({
        [constants.HOLIDAY_EVENT_NATIONAL]: Joi.number().integer().allow(null).required(),
        [constants.HOLIDAY_EVENT_HUNGKING]: Joi.number().integer().allow(null).required(),
        [constants.HOLIDAY_EVENT_LIBERATION]: Joi.number().integer().allow(null).required(),
        [constants.HOLIDAY_EVENT_NEWYEAR]: Joi.number().integer().allow(null).required(),
        [constants.HOLIDAY_EVENT_LUNAR]: Joi.number().integer().allow(null).required(),
      }).unknown(true).allow(null).required(),
      week_days_price: Joi.object().keys({
        "mon": Joi.number().integer().allow(null).required(),
        "tue": Joi.number().integer().allow(null).required(),
        "wed": Joi.number().integer().allow(null).required(),
        "thu": Joi.number().integer().allow(null).required(),
        "fri": Joi.number().integer().allow(null).required(),
        "sat": Joi.number().integer().allow(null).required(),
        "sun": Joi.number().integer().allow(null).required(),
      }).unknown(true).allow(null).required(),
      active: Joi.boolean(),
      agent_name: Joi.string().allow(null, ''),
      agent_phone: Joi.string().allow(null, ''),
      bank_account_name: Joi.string().allow(null, ''),
      bank_account_number: Joi.string().allow(null, ''),
      bank_name: Joi.string().allow(null, ''),
      bank_branch_name: Joi.string().allow(null, ''),
      tax_number: Joi.string().allow(null, ''),
      add_ons: Joi.array().items(Joi.object({
        code: Joi.string().required(),
        cost: Joi.number().integer().required(),
        unit: Joi.string(),
      })).allow(null),
      location: Joi.string().allow(null, ''),
      payment_methods: Joi.array().items(Joi.string()).allow(null),
    })
  },
  update: {
    body: Joi.object({
      name: Joi.string().max(255),
      code: Joi.string().max(255).regex(RegExp(/[\d\w]/)),
      province_id: Joi.number().integer().min(0),
      district_id: Joi.number().integer().min(0),
      address: Joi.string().max(255),
      latlng: Joi.string().max(100).regex(RegExp(latLngRegex)).allow('', null),
      rental_time_from: Joi.string().regex(RegExp(timeRegex)).allow('', null),
      rental_time_to: Joi.string().regex(RegExp(timeRegex)).allow('', null),
      limit_km: Joi.number().integer().min(0),
      overkm_fee: Joi.number().integer().min(0),
      overtime_fee: Joi.number().integer().min(0),
      free_delivery_km: Joi.number().integer().min(0),
      delivery_fee: Joi.number().integer().min(0),
      procedure: Joi.object().keys({
        [constants.PROCEDURE_IDENTITY]: Joi.valid(constants.PROCEDURE_TYPE_HOLD, constants.PROCEDURE_TYPE_VERIFY).allow(null, '').required(),
        [constants.PROCEDURE_HOUSEHOLD]: Joi.valid(constants.PROCEDURE_TYPE_HOLD, constants.PROCEDURE_TYPE_VERIFY).allow(null, '').required(),
        [constants.PROCEDURE_DRIVER_LICENCE]: Joi.valid(constants.PROCEDURE_TYPE_HOLD, constants.PROCEDURE_TYPE_VERIFY).allow(null, '').required(),
        [constants.PROCEDURE_DEPOSIT]: Joi.valid(constants.PROCEDURE_TYPE_HOLD, constants.PROCEDURE_TYPE_VERIFY).allow(null, '').required(),
        [constants.PROCEDURE_LABOR_CONTRACT]: Joi.valid(constants.PROCEDURE_TYPE_HOLD, constants.PROCEDURE_TYPE_VERIFY).allow(null, '').required(),
        [constants.PROCEDURE_OTHER]: Joi.valid(constants.PROCEDURE_TYPE_HOLD, constants.PROCEDURE_TYPE_VERIFY).allow(null, '').required(),
        [constants.PROCEDURE_IDENTITY + '_note']: Joi.string().allow(null, ''),
        [constants.PROCEDURE_HOUSEHOLD + '_note']: Joi.string().allow(null, ''),
        [constants.PROCEDURE_DRIVER_LICENCE + '_note']: Joi.string().allow(null, ''),
        [constants.PROCEDURE_DEPOSIT + '_note']: Joi.string().allow(null, ''),
        [constants.PROCEDURE_LABOR_CONTRACT + '_note']: Joi.string().allow(null, ''),
        [constants.PROCEDURE_OTHER + '_note']: Joi.string().allow(null, ''),
      }).unknown(true),
      holiday_event_price: Joi.object().keys({
        [constants.HOLIDAY_EVENT_NATIONAL]: Joi.number().integer().allow(null).required(),
        [constants.HOLIDAY_EVENT_HUNGKING]: Joi.number().integer().allow(null).required(),
        [constants.HOLIDAY_EVENT_LIBERATION]: Joi.number().integer().allow(null).required(),
        [constants.HOLIDAY_EVENT_NEWYEAR]: Joi.number().integer().allow(null).required(),
        [constants.HOLIDAY_EVENT_LUNAR]: Joi.number().integer().allow(null).required(),
      }).unknown(true),
      week_days_price: Joi.object().keys({
        "mon": Joi.number().integer().allow(null).required(),
        "tue": Joi.number().integer().allow(null).required(),
        "wed": Joi.number().integer().allow(null).required(),
        "thu": Joi.number().integer().allow(null).required(),
        "fri": Joi.number().integer().allow(null).required(),
        "sat": Joi.number().integer().allow(null).required(),
        "sun": Joi.number().integer().allow(null).required(),
      }).unknown(true),
      active: Joi.boolean(),
      agent_name: Joi.string().allow(null, ''),
      agent_phone: Joi.string().allow(null, ''),
      bank_account_name: Joi.string().allow(null, ''),
      bank_account_number: Joi.string().allow(null, ''),
      bank_name: Joi.string().allow(null, ''),
      bank_branch_name: Joi.string().allow(null, ''),
      tax_number: Joi.string().allow(null, ''),
      add_ons: Joi.array().items(Joi.object({
        code: Joi.string().required(),
        cost: Joi.number().integer().required(),
        unit: Joi.string(),
      })).allow(null),
      location: Joi.string().allow(null, ''),
      payment_methods: Joi.array().items(Joi.string()).allow(null),
    })
  },
}
